import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./(Layout)/Navbar";
import axios from "axios";
import { headers } from "next/headers";

import { Provider } from "react-redux";
import Store from "./Store/Store";
import ProviderWrapper from "./Store/ProviderWrapper";
import JobApiFetch from "./Api/JobApiFetch";
import ToastProvider from "./ToastProvider";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css"
          integrity="sha512-yTcg2+7RfXoLZKICiJfgF0v5...your-integrity-key..."
          crossOrigin="anonymous"
          referrerPolicy="no-referrer"
        />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Nunito+Sans:ital,opsz,wght@0,6..12,200..1000;1,6..12,200..1000&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Roboto:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet" />
      </head>
      <body>
        <ProviderWrapper >
          <JobApiFetch />
          <Navbar />
          {children}
          <ToastProvider />
        </ProviderWrapper>
      </body>
    </html>
  );
}
