import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./(Layout)/Navbar";
import axios from "axios";
import { headers } from "next/headers";

import { Provider } from "react-redux";
import Store from "./Store/Store";
import ProviderWrapper from "./Store/ProviderWrapper";
import JobApiFetch from "./Api/JobApiFetch";
import ToastProvider from "./ToastProvider";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default  function RootLayout({ children }) {

  return (
    <html lang="en">
      <head>
      <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css"
          integrity="sha512-yTcg2+7RfXoLZKICiJfgF0v5...your-integrity-key..."
          crossOrigin="anonymous"
          referrerPolicy="no-referrer"
        />
      </head>
      <body>
      <ProviderWrapper >
     <JobApiFetch/>
      <Navbar/>
      {children}
      <ToastProvider/>
      </ProviderWrapper> 
      </body>
    </html>
  );
}
